### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by reidsneo** [esyede/single-blade#2]
There will an error while the matched data is not a object nor array (string), should able to handler string input using strlen() instead of count()

https://github.com/esyede/single-blade/blob/523a8e2ccb08494f9e5fdf5e494589b3923af5d9/Blade.php#L81

**Comment by esyede** [comment]
@reidsneo Thanks. Can you provide an example code that causes this error please?

**Comment by esyede** [comment]
Fixed in dab5545
